"use client";

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { useState } from "react";
import "./globals.css";
import Navbar from "../components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// (metadata stays fine – no change needed)
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [collapsed, setCollapsed] = useState(false);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50 dark:bg-gray-950`}
      >
        {/* SIDEBAR */}
        <Navbar collapsed={collapsed} setCollapsed={setCollapsed} />

        {/* MAIN CONTENT */}
        <main
          className={`
            min-h-screen transition-all duration-300
            ${collapsed ? "ml-14" : "ml-66"}
          `}
        >
          {/* PAGE WRAPPER */}
          <div className="p-0">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
